apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperaturas-backend
  template:
    metadata:
      labels:
        app: temperaturas-backend
    spec:
      containers:
      - name: temperaturas-backend
        image: tu_usuario_dockerhub/temperaturas-backend:latest # CHANGE THIS
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"

---
apiVersion: v1
kind: Service
metadata:
  name: temperaturas-backend # Critical: Frontend uses this name
spec:
  selector:
    app: temperaturas-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
